### PR TITLE
Git versioning and azure

### PR DESCRIPTION
**Pull request by Oblarg**

### CODE REVIEW

**Comment by virtuald** [comment]
Why did you check in the egg-info files?

**Comment by auscompgeek** [comment]
Why did this check in an egg-info directory?

**Comment by Oblarg** [comment]
Because, for some reason, it wasn't in the .gitignore.

There's another PR to fix that.

**Comment by virtuald** [comment]
That was some of the cleanup type things I would have done after the setup.py was added. Wasn't needed when there wasn't a setup.py.

**Pull request merged**
